### ISSUE TITLE
Updating Tutorial

### ISSUE THREAD

**Issue by AustinYQM** [mjhea0/node-bootstrap3-template#2]
Is there a chance of you updating your tutorial at

https://mherman.org/blog/user-authentication-with-passport-dot-js/

I was attempting to follow it but things stopped being up to date before I made it through the app.js section. 

If you feel that these are no longer good technologies to do could you point me in a good direction for a tutorial using modern technologies to make a restful API?

Thanks!

**Comment by mjhea0** [comment]
Try https://blog.logrocket.com/creating-your-first-rest-api-with-deno-and-postgres/
